#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 11
#define STATE_COUNT 122
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 83
#define ALIAS_COUNT 0
#define TOKEN_COUNT 39
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6

enum {
  anon_sym_LBRACE = 1,
  anon_sym_RBRACE = 2,
  anon_sym_COLON = 3,
  anon_sym_LPAREN = 4,
  anon_sym_RPAREN = 5,
  anon_sym_LT = 6,
  anon_sym_GT = 7,
  anon_sym_not = 8,
  anon_sym_LBRACK = 9,
  anon_sym_RBRACK = 10,
  anon_sym_COMMA = 11,
  anon_sym_DOT = 12,
  anon_sym_PLUS = 13,
  anon_sym_DASH = 14,
  anon_sym_PIPE = 15,
  sym_disjunction_operator = 16,
  sym_conjuction_operator = 17,
  anon_sym_STAR = 18,
  anon_sym_SLASH = 19,
  anon_sym_PERCENT = 20,
  anon_sym_AMP = 21,
  anon_sym_EQ_EQ = 22,
  anon_sym_BANG_EQ = 23,
  anon_sym_GT_EQ = 24,
  anon_sym_LT_EQ = 25,
  anon_sym_in = 26,
  anon_sym_is = 27,
  sym_camel_identifier = 28,
  sym_pascal_identifier = 29,
  sym_decorator_identifier = 30,
  sym_macro_identifier = 31,
  anon_sym_DQUOTE = 32,
  aux_sym_double_quote_string_token1 = 33,
  anon_sym_SQUOTE = 34,
  aux_sym_single_quote_string_token1 = 35,
  anon_sym_BQUOTE = 36,
  sym_integer = 37,
  sym_escape_sequence = 38,
  sym_program = 39,
  sym_block = 40,
  sym_body = 41,
  sym_body_element = 42,
  sym_property = 43,
  sym_property_type = 44,
  sym_decorator = 45,
  sym_decorator_args = 46,
  sym_generic_args = 47,
  sym_extends_args = 48,
  sym_expression = 49,
  sym_boolean_expression = 50,
  sym_disjunction_expression = 51,
  sym_conjuction_expression = 52,
  sym_negation_expression = 53,
  sym_relational_expression = 54,
  sym_arithmetic_expression = 55,
  sym_additive_expression = 56,
  sym_multiplicative_expression = 57,
  sym_factor = 58,
  sym_function_call = 59,
  sym_unary_expression = 60,
  sym_unsigned_constant = 61,
  sym_list = 62,
  sym_expression_list = 63,
  sym_identifier = 64,
  sym_identifier_name = 65,
  sym_additive_operator = 66,
  sym_unary_operator = 67,
  sym_multiplicative_operator = 68,
  sym_relational_operator = 69,
  sym_literal = 70,
  sym_number = 71,
  sym_string = 72,
  sym_double_quote_string = 73,
  sym_single_quote_string = 74,
  sym_template_string = 75,
  aux_sym_program_repeat1 = 76,
  aux_sym_block_repeat1 = 77,
  aux_sym_body_repeat1 = 78,
  aux_sym_expression_list_repeat1 = 79,
  aux_sym_identifier_repeat1 = 80,
  aux_sym_double_quote_string_repeat1 = 81,
  aux_sym_single_quote_string_repeat1 = 82,
};

static const char *ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_not] = "not",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COMMA] = ",",
  [anon_sym_DOT] = ".",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_PIPE] = "|",
  [sym_disjunction_operator] = "disjunction_operator",
  [sym_conjuction_operator] = "conjuction_operator",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PERCENT] = "%",
  [anon_sym_AMP] = "&",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_in] = "in",
  [anon_sym_is] = "is",
  [sym_camel_identifier] = "camel_identifier",
  [sym_pascal_identifier] = "pascal_identifier",
  [sym_decorator_identifier] = "decorator_identifier",
  [sym_macro_identifier] = "macro_identifier",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_double_quote_string_token1] = "double_quote_string_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_single_quote_string_token1] = "single_quote_string_token1",
  [anon_sym_BQUOTE] = "`",
  [sym_integer] = "integer",
  [sym_escape_sequence] = "escape_sequence",
  [sym_program] = "program",
  [sym_block] = "block",
  [sym_body] = "body",
  [sym_body_element] = "body_element",
  [sym_property] = "property",
  [sym_property_type] = "property_type",
  [sym_decorator] = "decorator",
  [sym_decorator_args] = "decorator_args",
  [sym_generic_args] = "generic_args",
  [sym_extends_args] = "extends_args",
  [sym_expression] = "expression",
  [sym_boolean_expression] = "boolean_expression",
  [sym_disjunction_expression] = "disjunction_expression",
  [sym_conjuction_expression] = "conjuction_expression",
  [sym_negation_expression] = "negation_expression",
  [sym_relational_expression] = "relational_expression",
  [sym_arithmetic_expression] = "arithmetic_expression",
  [sym_additive_expression] = "additive_expression",
  [sym_multiplicative_expression] = "multiplicative_expression",
  [sym_factor] = "factor",
  [sym_function_call] = "function_call",
  [sym_unary_expression] = "unary_expression",
  [sym_unsigned_constant] = "unsigned_constant",
  [sym_list] = "list",
  [sym_expression_list] = "expression_list",
  [sym_identifier] = "identifier",
  [sym_identifier_name] = "identifier_name",
  [sym_additive_operator] = "additive_operator",
  [sym_unary_operator] = "unary_operator",
  [sym_multiplicative_operator] = "multiplicative_operator",
  [sym_relational_operator] = "relational_operator",
  [sym_literal] = "literal",
  [sym_number] = "number",
  [sym_string] = "string",
  [sym_double_quote_string] = "double_quote_string",
  [sym_single_quote_string] = "single_quote_string",
  [sym_template_string] = "template_string",
  [aux_sym_program_repeat1] = "program_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_body_repeat1] = "body_repeat1",
  [aux_sym_expression_list_repeat1] = "expression_list_repeat1",
  [aux_sym_identifier_repeat1] = "identifier_repeat1",
  [aux_sym_double_quote_string_repeat1] = "double_quote_string_repeat1",
  [aux_sym_single_quote_string_repeat1] = "single_quote_string_repeat1",
};

static TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_not] = anon_sym_not,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym_disjunction_operator] = sym_disjunction_operator,
  [sym_conjuction_operator] = sym_conjuction_operator,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_is] = anon_sym_is,
  [sym_camel_identifier] = sym_camel_identifier,
  [sym_pascal_identifier] = sym_pascal_identifier,
  [sym_decorator_identifier] = sym_decorator_identifier,
  [sym_macro_identifier] = sym_macro_identifier,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_double_quote_string_token1] = aux_sym_double_quote_string_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_single_quote_string_token1] = aux_sym_single_quote_string_token1,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [sym_integer] = sym_integer,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_program] = sym_program,
  [sym_block] = sym_block,
  [sym_body] = sym_body,
  [sym_body_element] = sym_body_element,
  [sym_property] = sym_property,
  [sym_property_type] = sym_property_type,
  [sym_decorator] = sym_decorator,
  [sym_decorator_args] = sym_decorator_args,
  [sym_generic_args] = sym_generic_args,
  [sym_extends_args] = sym_extends_args,
  [sym_expression] = sym_expression,
  [sym_boolean_expression] = sym_boolean_expression,
  [sym_disjunction_expression] = sym_disjunction_expression,
  [sym_conjuction_expression] = sym_conjuction_expression,
  [sym_negation_expression] = sym_negation_expression,
  [sym_relational_expression] = sym_relational_expression,
  [sym_arithmetic_expression] = sym_arithmetic_expression,
  [sym_additive_expression] = sym_additive_expression,
  [sym_multiplicative_expression] = sym_multiplicative_expression,
  [sym_factor] = sym_factor,
  [sym_function_call] = sym_function_call,
  [sym_unary_expression] = sym_unary_expression,
  [sym_unsigned_constant] = sym_unsigned_constant,
  [sym_list] = sym_list,
  [sym_expression_list] = sym_expression_list,
  [sym_identifier] = sym_identifier,
  [sym_identifier_name] = sym_identifier_name,
  [sym_additive_operator] = sym_additive_operator,
  [sym_unary_operator] = sym_unary_operator,
  [sym_multiplicative_operator] = sym_multiplicative_operator,
  [sym_relational_operator] = sym_relational_operator,
  [sym_literal] = sym_literal,
  [sym_number] = sym_number,
  [sym_string] = sym_string,
  [sym_double_quote_string] = sym_double_quote_string,
  [sym_single_quote_string] = sym_single_quote_string,
  [sym_template_string] = sym_template_string,
  [aux_sym_program_repeat1] = aux_sym_program_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_body_repeat1] = aux_sym_body_repeat1,
  [aux_sym_expression_list_repeat1] = aux_sym_expression_list_repeat1,
  [aux_sym_identifier_repeat1] = aux_sym_identifier_repeat1,
  [aux_sym_double_quote_string_repeat1] = aux_sym_double_quote_string_repeat1,
  [aux_sym_single_quote_string_repeat1] = aux_sym_single_quote_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_not] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_disjunction_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_conjuction_operator] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_is] = {
    .visible = true,
    .named = false,
  },
  [sym_camel_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_pascal_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_decorator_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_macro_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_double_quote_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_single_quote_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_program] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [sym_body_element] = {
    .visible = true,
    .named = true,
  },
  [sym_property] = {
    .visible = true,
    .named = true,
  },
  [sym_property_type] = {
    .visible = true,
    .named = true,
  },
  [sym_decorator] = {
    .visible = true,
    .named = true,
  },
  [sym_decorator_args] = {
    .visible = true,
    .named = true,
  },
  [sym_generic_args] = {
    .visible = true,
    .named = true,
  },
  [sym_extends_args] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_disjunction_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_conjuction_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_negation_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_relational_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_arithmetic_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_additive_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_multiplicative_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_factor] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_unsigned_constant] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_list] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier_name] = {
    .visible = true,
    .named = true,
  },
  [sym_additive_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_multiplicative_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_relational_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_double_quote_string] = {
    .visible = true,
    .named = true,
  },
  [sym_single_quote_string] = {
    .visible = true,
    .named = true,
  },
  [sym_template_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_program_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expression_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_identifier_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_double_quote_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_single_quote_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static TSSymbol ts_alias_sequences[1][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(24);
      if (lookahead == '!') ADVANCE(8);
      if (lookahead == '"') ADVANCE(60);
      if (lookahead == '$') ADVANCE(20);
      if (lookahead == '%') ADVANCE(46);
      if (lookahead == '&') ADVANCE(47);
      if (lookahead == '\'') ADVANCE(64);
      if (lookahead == '(') ADVANCE(28);
      if (lookahead == ')') ADVANCE(29);
      if (lookahead == '*') ADVANCE(44);
      if (lookahead == '+') ADVANCE(39);
      if (lookahead == ',') ADVANCE(37);
      if (lookahead == '-') ADVANCE(40);
      if (lookahead == '.') ADVANCE(38);
      if (lookahead == '/') ADVANCE(45);
      if (lookahead == ':') ADVANCE(27);
      if (lookahead == '<') ADVANCE(31);
      if (lookahead == '=') ADVANCE(9);
      if (lookahead == '>') ADVANCE(32);
      if (lookahead == '@') ADVANCE(21);
      if (lookahead == '[') ADVANCE(35);
      if (lookahead == '\\') ADVANCE(13);
      if (lookahead == ']') ADVANCE(36);
      if (lookahead == '`') ADVANCE(68);
      if (lookahead == 'i') ADVANCE(10);
      if (lookahead == 'n') ADVANCE(11);
      if (lookahead == '{') ADVANCE(25);
      if (lookahead == '|') ADVANCE(41);
      if (lookahead == '}') ADVANCE(26);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(22)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(57);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(7)
      if (lookahead == '\'') ADVANCE(64);
      if (lookahead == '\\') ADVANCE(2);
      if (lookahead == '`') ADVANCE(67);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(66);
      if (lookahead != 0) ADVANCE(67);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(65);
      if (lookahead == '\r') ADVANCE(71);
      if (lookahead == 'u') ADVANCE(14);
      if (lookahead == 'x') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(74);
      if (lookahead != 0) ADVANCE(70);
      END_STATE();
    case 3:
      if (lookahead == '\n') SKIP(6)
      if (lookahead == '"') ADVANCE(60);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(62);
      if (lookahead != 0) ADVANCE(63);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(61);
      if (lookahead == '\r') ADVANCE(72);
      if (lookahead == 'u') ADVANCE(14);
      if (lookahead == 'x') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(74);
      if (lookahead != 0) ADVANCE(70);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(60);
      if (lookahead == '\'') ADVANCE(64);
      if (lookahead == '(') ADVANCE(28);
      if (lookahead == ')') ADVANCE(29);
      if (lookahead == '+') ADVANCE(39);
      if (lookahead == '-') ADVANCE(40);
      if (lookahead == '[') ADVANCE(35);
      if (lookahead == '`') ADVANCE(68);
      if (lookahead == 'n') ADVANCE(54);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(57);
      if (('_' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(60);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(6)
      END_STATE();
    case 7:
      if (lookahead == '\'') ADVANCE(64);
      if (lookahead == '`') ADVANCE(68);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(7)
      END_STATE();
    case 8:
      if (lookahead == '=') ADVANCE(49);
      END_STATE();
    case 9:
      if (lookahead == '=') ADVANCE(48);
      END_STATE();
    case 10:
      if (lookahead == 'n') ADVANCE(52);
      if (lookahead == 's') ADVANCE(53);
      END_STATE();
    case 11:
      if (lookahead == 'o') ADVANCE(12);
      END_STATE();
    case 12:
      if (lookahead == 't') ADVANCE(33);
      END_STATE();
    case 13:
      if (lookahead == 'u') ADVANCE(14);
      if (lookahead == 'x') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(74);
      if (lookahead != 0) ADVANCE(70);
      END_STATE();
    case 14:
      if (lookahead == '{') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(16);
      END_STATE();
    case 15:
      if (lookahead == '}') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(15);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(19);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(70);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(15);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(17);
      END_STATE();
    case 20:
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 21:
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 22:
      if (eof) ADVANCE(24);
      if (lookahead == '!') ADVANCE(8);
      if (lookahead == '"') ADVANCE(60);
      if (lookahead == '$') ADVANCE(20);
      if (lookahead == '%') ADVANCE(46);
      if (lookahead == '&') ADVANCE(47);
      if (lookahead == '\'') ADVANCE(64);
      if (lookahead == '(') ADVANCE(28);
      if (lookahead == ')') ADVANCE(29);
      if (lookahead == '*') ADVANCE(44);
      if (lookahead == '+') ADVANCE(39);
      if (lookahead == ',') ADVANCE(37);
      if (lookahead == '-') ADVANCE(40);
      if (lookahead == '.') ADVANCE(38);
      if (lookahead == '/') ADVANCE(45);
      if (lookahead == ':') ADVANCE(27);
      if (lookahead == '<') ADVANCE(31);
      if (lookahead == '=') ADVANCE(9);
      if (lookahead == '>') ADVANCE(32);
      if (lookahead == '@') ADVANCE(21);
      if (lookahead == '[') ADVANCE(35);
      if (lookahead == ']') ADVANCE(36);
      if (lookahead == '`') ADVANCE(68);
      if (lookahead == 'i') ADVANCE(10);
      if (lookahead == 'n') ADVANCE(11);
      if (lookahead == '{') ADVANCE(25);
      if (lookahead == '|') ADVANCE(41);
      if (lookahead == '}') ADVANCE(26);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(22)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(57);
      END_STATE();
    case 23:
      if (eof) ADVANCE(24);
      if (lookahead == '"') ADVANCE(60);
      if (lookahead == '\'') ADVANCE(64);
      if (lookahead == '(') ADVANCE(28);
      if (lookahead == '+') ADVANCE(39);
      if (lookahead == '-') ADVANCE(40);
      if (lookahead == '<') ADVANCE(30);
      if (lookahead == '@') ADVANCE(21);
      if (lookahead == '[') ADVANCE(35);
      if (lookahead == '`') ADVANCE(68);
      if (lookahead == '{') ADVANCE(25);
      if (lookahead == '}') ADVANCE(26);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(23)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      if (('A' <= lookahead && lookahead <= 'Z')) ADVANCE(57);
      if (('_' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(51);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(50);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_not);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_not);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_PIPE);
      if (lookahead == '|') ADVANCE(42);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_disjunction_operator);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_conjuction_operator);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_AMP);
      if (lookahead == '&') ADVANCE(43);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_is);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_camel_identifier);
      if (lookahead == 'o') ADVANCE(55);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_camel_identifier);
      if (lookahead == 't') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_camel_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_pascal_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_decorator_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_macro_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_double_quote_string_token1);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_double_quote_string_token1);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(63);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_double_quote_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(aux_sym_single_quote_string_token1);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(aux_sym_single_quote_string_token1);
      if (lookahead == '`') ADVANCE(67);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(66);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(67);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_single_quote_string_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (lookahead == '\n') ADVANCE(65);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (lookahead == '\n') ADVANCE(61);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(70);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(73);
      END_STATE();
    default:
      return false;
  }
}

static TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 23},
  [2] = {.lex_state = 5},
  [3] = {.lex_state = 5},
  [4] = {.lex_state = 5},
  [5] = {.lex_state = 5},
  [6] = {.lex_state = 5},
  [7] = {.lex_state = 5},
  [8] = {.lex_state = 5},
  [9] = {.lex_state = 5},
  [10] = {.lex_state = 5},
  [11] = {.lex_state = 23},
  [12] = {.lex_state = 23},
  [13] = {.lex_state = 23},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 23},
  [16] = {.lex_state = 23},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 5},
  [48] = {.lex_state = 23},
  [49] = {.lex_state = 23},
  [50] = {.lex_state = 23},
  [51] = {.lex_state = 23},
  [52] = {.lex_state = 23},
  [53] = {.lex_state = 23},
  [54] = {.lex_state = 23},
  [55] = {.lex_state = 23},
  [56] = {.lex_state = 23},
  [57] = {.lex_state = 23},
  [58] = {.lex_state = 23},
  [59] = {.lex_state = 23},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 23},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 23},
  [69] = {.lex_state = 23},
  [70] = {.lex_state = 23},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 23},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 23},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 23},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 23},
  [82] = {.lex_state = 23},
  [83] = {.lex_state = 23},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 23},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 23},
  [88] = {.lex_state = 3},
  [89] = {.lex_state = 1},
  [90] = {.lex_state = 23},
  [91] = {.lex_state = 23},
  [92] = {.lex_state = 1},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 3},
  [95] = {.lex_state = 3},
  [96] = {.lex_state = 23},
  [97] = {.lex_state = 23},
  [98] = {.lex_state = 23},
  [99] = {.lex_state = 23},
  [100] = {.lex_state = 23},
  [101] = {.lex_state = 23},
  [102] = {.lex_state = 23},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 23},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 23},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 23},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
};

static uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_not] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [sym_disjunction_operator] = ACTIONS(1),
    [sym_conjuction_operator] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_is] = ACTIONS(1),
    [sym_pascal_identifier] = ACTIONS(1),
    [sym_decorator_identifier] = ACTIONS(1),
    [sym_macro_identifier] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
  },
  [1] = {
    [sym_program] = STATE(114),
    [sym_block] = STATE(58),
    [sym_decorator] = STATE(83),
    [aux_sym_program_repeat1] = STATE(58),
    [aux_sym_block_repeat1] = STATE(83),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_camel_identifier] = ACTIONS(5),
    [sym_decorator_identifier] = ACTIONS(7),
  },
};

static uint16_t ts_small_parse_table[] = {
  [0] = 29,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_RPAREN,
    ACTIONS(13), 1,
      anon_sym_not,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      sym_camel_identifier,
    ACTIONS(21), 1,
      sym_pascal_identifier,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_SQUOTE,
    ACTIONS(27), 1,
      anon_sym_BQUOTE,
    ACTIONS(29), 1,
      sym_integer,
    STATE(14), 1,
      sym_identifier_name,
    STATE(16), 1,
      sym_unary_operator,
    STATE(21), 1,
      sym_identifier,
    STATE(23), 1,
      sym_multiplicative_expression,
    STATE(37), 1,
      sym_literal,
    STATE(38), 1,
      sym_factor,
    STATE(42), 1,
      sym_additive_expression,
    STATE(44), 1,
      sym_relational_expression,
    STATE(46), 1,
      sym_arithmetic_expression,
    STATE(61), 1,
      sym_negation_expression,
    STATE(63), 1,
      sym_conjuction_expression,
    STATE(67), 1,
      sym_disjunction_expression,
    STATE(74), 1,
      sym_expression,
    STATE(93), 1,
      sym_boolean_expression,
    STATE(116), 1,
      sym_expression_list,
    ACTIONS(17), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(36), 2,
      sym_number,
      sym_string,
    STATE(25), 3,
      sym_double_quote_string,
      sym_single_quote_string,
      sym_template_string,
    STATE(39), 4,
      sym_function_call,
      sym_unary_expression,
      sym_unsigned_constant,
      sym_list,
  [95] = 29,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_not,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      sym_camel_identifier,
    ACTIONS(21), 1,
      sym_pascal_identifier,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_SQUOTE,
    ACTIONS(27), 1,
      anon_sym_BQUOTE,
    ACTIONS(29), 1,
      sym_integer,
    ACTIONS(31), 1,
      anon_sym_RPAREN,
    STATE(14), 1,
      sym_identifier_name,
    STATE(16), 1,
      sym_unary_operator,
    STATE(21), 1,
      sym_identifier,
    STATE(23), 1,
      sym_multiplicative_expression,
    STATE(37), 1,
      sym_literal,
    STATE(38), 1,
      sym_factor,
    STATE(42), 1,
      sym_additive_expression,
    STATE(44), 1,
      sym_relational_expression,
    STATE(46), 1,
      sym_arithmetic_expression,
    STATE(61), 1,
      sym_negation_expression,
    STATE(63), 1,
      sym_conjuction_expression,
    STATE(67), 1,
      sym_disjunction_expression,
    STATE(74), 1,
      sym_expression,
    STATE(93), 1,
      sym_boolean_expression,
    STATE(113), 1,
      sym_expression_list,
    ACTIONS(17), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(36), 2,
      sym_number,
      sym_string,
    STATE(25), 3,
      sym_double_quote_string,
      sym_single_quote_string,
      sym_template_string,
    STATE(39), 4,
      sym_function_call,
      sym_unary_expression,
      sym_unsigned_constant,
      sym_list,
  [190] = 28,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_not,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      sym_camel_identifier,
    ACTIONS(21), 1,
      sym_pascal_identifier,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_SQUOTE,
    ACTIONS(27), 1,
      anon_sym_BQUOTE,
    ACTIONS(29), 1,
      sym_integer,
    STATE(14), 1,
      sym_identifier_name,
    STATE(16), 1,
      sym_unary_operator,
    STATE(21), 1,
      sym_identifier,
    STATE(23), 1,
      sym_multiplicative_expression,
    STATE(37), 1,
      sym_literal,
    STATE(38), 1,
      sym_factor,
    STATE(42), 1,
      sym_additive_expression,
    STATE(44), 1,
      sym_relational_expression,
    STATE(46), 1,
      sym_arithmetic_expression,
    STATE(61), 1,
      sym_negation_expression,
    STATE(63), 1,
      sym_conjuction_expression,
    STATE(67), 1,
      sym_disjunction_expression,
    STATE(74), 1,
      sym_expression,
    STATE(93), 1,
      sym_boolean_expression,
    STATE(120), 1,
      sym_expression_list,
    ACTIONS(17), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(36), 2,
      sym_number,
      sym_string,
    STATE(25), 3,
      sym_double_quote_string,
      sym_single_quote_string,
      sym_template_string,
    STATE(39), 4,
      sym_function_call,
      sym_unary_expression,
      sym_unsigned_constant,
      sym_list,
  [282] = 28,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_not,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      sym_camel_identifier,
    ACTIONS(21), 1,
      sym_pascal_identifier,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_SQUOTE,
    ACTIONS(27), 1,
      anon_sym_BQUOTE,
    ACTIONS(29), 1,
      sym_integer,
    STATE(14), 1,
      sym_identifier_name,
    STATE(16), 1,
      sym_unary_operator,
    STATE(21), 1,
      sym_identifier,
    STATE(23), 1,
      sym_multiplicative_expression,
    STATE(37), 1,
      sym_literal,
    STATE(38), 1,
      sym_factor,
    STATE(42), 1,
      sym_additive_expression,
    STATE(44), 1,
      sym_relational_expression,
    STATE(46), 1,
      sym_arithmetic_expression,
    STATE(61), 1,
      sym_negation_expression,
    STATE(63), 1,
      sym_conjuction_expression,
    STATE(67), 1,
      sym_disjunction_expression,
    STATE(74), 1,
      sym_expression,
    STATE(93), 1,
      sym_boolean_expression,
    STATE(121), 1,
      sym_expression_list,
    ACTIONS(17), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(36), 2,
      sym_number,
      sym_string,
    STATE(25), 3,
      sym_double_quote_string,
      sym_single_quote_string,
      sym_template_string,
    STATE(39), 4,
      sym_function_call,
      sym_unary_expression,
      sym_unsigned_constant,
      sym_list,
  [374] = 28,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_not,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      sym_camel_identifier,
    ACTIONS(21), 1,
      sym_pascal_identifier,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_SQUOTE,
    ACTIONS(27), 1,
      anon_sym_BQUOTE,
    ACTIONS(29), 1,
      sym_integer,
    STATE(14), 1,
      sym_identifier_name,
    STATE(16), 1,
      sym_unary_operator,
    STATE(21), 1,
      sym_identifier,
    STATE(23), 1,
      sym_multiplicative_expression,
    STATE(37), 1,
      sym_literal,
    STATE(38), 1,
      sym_factor,
    STATE(42), 1,
      sym_additive_expression,
    STATE(44), 1,
      sym_relational_expression,
    STATE(46), 1,
      sym_arithmetic_expression,
    STATE(61), 1,
      sym_negation_expression,
    STATE(63), 1,
      sym_conjuction_expression,
    STATE(67), 1,
      sym_disjunction_expression,
    STATE(74), 1,
      sym_expression,
    STATE(93), 1,
      sym_boolean_expression,
    STATE(117), 1,
      sym_expression_list,
    ACTIONS(17), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(36), 2,
      sym_number,
      sym_string,
    STATE(25), 3,
      sym_double_quote_string,
      sym_single_quote_string,
      sym_template_string,
    STATE(39), 4,
      sym_function_call,
      sym_unary_expression,
      sym_unsigned_constant,
      sym_list,
  [466] = 27,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_not,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      sym_camel_identifier,
    ACTIONS(21), 1,
      sym_pascal_identifier,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_SQUOTE,
    ACTIONS(27), 1,
      anon_sym_BQUOTE,
    ACTIONS(29), 1,
      sym_integer,
    STATE(14), 1,
      sym_identifier_name,
    STATE(16), 1,
      sym_unary_operator,
    STATE(21), 1,
      sym_identifier,
    STATE(23), 1,
      sym_multiplicative_expression,
    STATE(37), 1,
      sym_literal,
    STATE(38), 1,
      sym_factor,
    STATE(42), 1,
      sym_additive_expression,
    STATE(44), 1,
      sym_relational_expression,
    STATE(46), 1,
      sym_arithmetic_expression,
    STATE(61), 1,
      sym_negation_expression,
    STATE(63), 1,
      sym_conjuction_expression,
    STATE(67), 1,
      sym_disjunction_expression,
    STATE(76), 1,
      sym_expression,
    STATE(93), 1,
      sym_boolean_expression,
    ACTIONS(17), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(36), 2,
      sym_number,
      sym_string,
    STATE(25), 3,
      sym_double_quote_string,
      sym_single_quote_string,
      sym_template_string,
    STATE(39), 4,
      sym_function_call,
      sym_unary_expression,
      sym_unsigned_constant,
      sym_list,
  [555] = 27,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_not,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      sym_camel_identifier,
    ACTIONS(21), 1,
      sym_pascal_identifier,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_SQUOTE,
    ACTIONS(27), 1,
      anon_sym_BQUOTE,
    ACTIONS(29), 1,
      sym_integer,
    STATE(14), 1,
      sym_identifier_name,
    STATE(16), 1,
      sym_unary_operator,
    STATE(21), 1,
      sym_identifier,
    STATE(23), 1,
      sym_multiplicative_expression,
    STATE(37), 1,
      sym_literal,
    STATE(38), 1,
      sym_factor,
    STATE(42), 1,
      sym_additive_expression,
    STATE(44), 1,
      sym_relational_expression,
    STATE(46), 1,
      sym_arithmetic_expression,
    STATE(61), 1,
      sym_negation_expression,
    STATE(63), 1,
      sym_conjuction_expression,
    STATE(67), 1,
      sym_disjunction_expression,
    STATE(93), 1,
      sym_boolean_expression,
    STATE(115), 1,
      sym_expression,
    ACTIONS(17), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(36), 2,
      sym_number,
      sym_string,
    STATE(25), 3,
      sym_double_quote_string,
      sym_single_quote_string,
      sym_template_string,
    STATE(39), 4,
      sym_function_call,
      sym_unary_expression,
      sym_unsigned_constant,
      sym_list,
  [644] = 24,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_not,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      sym_camel_identifier,
    ACTIONS(21), 1,
      sym_pascal_identifier,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_SQUOTE,
    ACTIONS(27), 1,
      anon_sym_BQUOTE,
    ACTIONS(29), 1,
      sym_integer,
    STATE(14), 1,
      sym_identifier_name,
    STATE(16), 1,
      sym_unary_operator,
    STATE(21), 1,
      sym_identifier,
    STATE(23), 1,
      sym_multiplicative_expression,
    STATE(37), 1,
      sym_literal,
    STATE(38), 1,
      sym_factor,
    STATE(42), 1,
      sym_additive_expression,
    STATE(44), 1,
      sym_relational_expression,
    STATE(46), 1,
      sym_arithmetic_expression,
    STATE(61), 1,
      sym_negation_expression,
    STATE(64), 1,
      sym_conjuction_expression,
    ACTIONS(17), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(36), 2,
      sym_number,
      sym_string,
    STATE(25), 3,
      sym_double_quote_string,
      sym_single_quote_string,
      sym_template_string,
    STATE(39), 4,
      sym_function_call,
      sym_unary_expression,
      sym_unsigned_constant,
      sym_list,
  [724] = 23,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_not,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      sym_camel_identifier,
    ACTIONS(21), 1,
      sym_pascal_identifier,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_SQUOTE,
    ACTIONS(27), 1,
      anon_sym_BQUOTE,
    ACTIONS(29), 1,
      sym_integer,
    STATE(14), 1,
      sym_identifier_name,
    STATE(16), 1,
      sym_unary_operator,
    STATE(21), 1,
      sym_identifier,
    STATE(23), 1,
      sym_multiplicative_expression,
    STATE(37), 1,
      sym_literal,
    STATE(38), 1,
      sym_factor,
    STATE(42), 1,
      sym_additive_expression,
    STATE(44), 1,
      sym_relational_expression,
    STATE(46), 1,
      sym_arithmetic_expression,
    STATE(62), 1,
      sym_negation_expression,
    ACTIONS(17), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    STATE(36), 2,
      sym_number,
      sym_string,
    STATE(25), 3,
      sym_double_quote_string,
      sym_single_quote_string,
      sym_template_string,
    STATE(39), 4,
      sym_function_call,
      sym_unary_expression,
      sym_unsigned_constant,
      sym_list,
  [801] = 20,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_SQUOTE,
    ACTIONS(27), 1,
      anon_sym_BQUOTE,
    ACTIONS(29), 1,
      sym_integer,
    STATE(14), 1,
      sym_identifier_name,
    STATE(16), 1,
      sym_unary_operator,
    STATE(21), 1,
      sym_identifier,
    STATE(23), 1,
      sym_multiplicative_expression,
    STATE(37), 1,
      sym_literal,
    STATE(38), 1,
      sym_factor,
    STATE(42), 1,
      sym_additive_expression,
    STATE(43), 1,
      sym_relational_expression,
    STATE(46), 1,
      sym_arithmetic_expression,
    ACTIONS(17), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(21), 2,
      sym_camel_identifier,
      sym_pascal_identifier,
    STATE(36), 2,
      sym_number,
      sym_string,
    STATE(25), 3,
      sym_double_quote_string,
      sym_single_quote_string,
      sym_template_string,
    STATE(39), 4,
      sym_function_call,
      sym_unary_expression,
      sym_unsigned_constant,
      sym_list,
  [870] = 19,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_SQUOTE,
    ACTIONS(27), 1,
      anon_sym_BQUOTE,
    ACTIONS(29), 1,
      sym_integer,
    STATE(14), 1,
      sym_identifier_name,
    STATE(16), 1,
      sym_unary_operator,
    STATE(21), 1,
      sym_identifier,
    STATE(23), 1,
      sym_multiplicative_expression,
    STATE(37), 1,
      sym_literal,
    STATE(38), 1,
      sym_factor,
    STATE(42), 1,
      sym_additive_expression,
    STATE(45), 1,
      sym_arithmetic_expression,
    ACTIONS(17), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(21), 2,
      sym_camel_identifier,
      sym_pascal_identifier,
    STATE(36), 2,
      sym_number,
      sym_string,
    STATE(25), 3,
      sym_double_quote_string,
      sym_single_quote_string,
      sym_template_string,
    STATE(39), 4,
      sym_function_call,
      sym_unary_expression,
      sym_unsigned_constant,
      sym_list,
  [936] = 17,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_SQUOTE,
    ACTIONS(27), 1,
      anon_sym_BQUOTE,
    ACTIONS(29), 1,
      sym_integer,
    STATE(14), 1,
      sym_identifier_name,
    STATE(16), 1,
      sym_unary_operator,
    STATE(21), 1,
      sym_identifier,
    STATE(22), 1,
      sym_multiplicative_expression,
    STATE(37), 1,
      sym_literal,
    STATE(38), 1,
      sym_factor,
    ACTIONS(17), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(21), 2,
      sym_camel_identifier,
      sym_pascal_identifier,
    STATE(36), 2,
      sym_number,
      sym_string,
    STATE(25), 3,
      sym_double_quote_string,
      sym_single_quote_string,
      sym_template_string,
    STATE(39), 4,
      sym_function_call,
      sym_unary_expression,
      sym_unsigned_constant,
      sym_list,
  [996] = 4,
    ACTIONS(37), 1,
      anon_sym_DOT,
    STATE(17), 1,
      aux_sym_identifier_repeat1,
    ACTIONS(35), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(33), 18,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_not,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_disjunction_operator,
      sym_conjuction_operator,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_in,
      anon_sym_is,
  [1029] = 16,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_SQUOTE,
    ACTIONS(27), 1,
      anon_sym_BQUOTE,
    ACTIONS(29), 1,
      sym_integer,
    STATE(14), 1,
      sym_identifier_name,
    STATE(16), 1,
      sym_unary_operator,
    STATE(21), 1,
      sym_identifier,
    STATE(37), 1,
      sym_literal,
    STATE(40), 1,
      sym_factor,
    ACTIONS(17), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(21), 2,
      sym_camel_identifier,
      sym_pascal_identifier,
    STATE(36), 2,
      sym_number,
      sym_string,
    STATE(25), 3,
      sym_double_quote_string,
      sym_single_quote_string,
      sym_template_string,
    STATE(39), 4,
      sym_function_call,
      sym_unary_expression,
      sym_unsigned_constant,
      sym_list,
  [1086] = 16,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(15), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_DQUOTE,
    ACTIONS(25), 1,
      anon_sym_SQUOTE,
    ACTIONS(27), 1,
      anon_sym_BQUOTE,
    ACTIONS(29), 1,
      sym_integer,
    STATE(14), 1,
      sym_identifier_name,
    STATE(16), 1,
      sym_unary_operator,
    STATE(21), 1,
      sym_identifier,
    STATE(35), 1,
      sym_factor,
    STATE(37), 1,
      sym_literal,
    ACTIONS(17), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(21), 2,
      sym_camel_identifier,
      sym_pascal_identifier,
    STATE(36), 2,
      sym_number,
      sym_string,
    STATE(25), 3,
      sym_double_quote_string,
      sym_single_quote_string,
      sym_template_string,
    STATE(39), 4,
      sym_function_call,
      sym_unary_expression,
      sym_unsigned_constant,
      sym_list,
  [1143] = 4,
    ACTIONS(37), 1,
      anon_sym_DOT,
    STATE(18), 1,
      aux_sym_identifier_repeat1,
    ACTIONS(41), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(39), 18,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_not,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_disjunction_operator,
      sym_conjuction_operator,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_in,
      anon_sym_is,
  [1176] = 4,
    ACTIONS(47), 1,
      anon_sym_DOT,
    STATE(18), 1,
      aux_sym_identifier_repeat1,
    ACTIONS(45), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(43), 18,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_not,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_disjunction_operator,
      sym_conjuction_operator,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_in,
      anon_sym_is,
  [1209] = 2,
    ACTIONS(52), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(50), 19,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_not,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_disjunction_operator,
      sym_conjuction_operator,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_in,
      anon_sym_is,
  [1237] = 2,
    ACTIONS(45), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(43), 19,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_not,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_disjunction_operator,
      sym_conjuction_operator,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_in,
      anon_sym_is,
  [1265] = 3,
    ACTIONS(54), 1,
      anon_sym_LPAREN,
    ACTIONS(58), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(56), 17,
      anon_sym_RPAREN,
      anon_sym_not,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_disjunction_operator,
      sym_conjuction_operator,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_in,
      anon_sym_is,
  [1294] = 5,
    ACTIONS(66), 1,
      anon_sym_AMP,
    STATE(15), 1,
      sym_multiplicative_operator,
    ACTIONS(62), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PIPE,
    ACTIONS(64), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(60), 14,
      anon_sym_RPAREN,
      anon_sym_not,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_disjunction_operator,
      sym_conjuction_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_in,
      anon_sym_is,
  [1327] = 5,
    ACTIONS(66), 1,
      anon_sym_AMP,
    STATE(15), 1,
      sym_multiplicative_operator,
    ACTIONS(64), 3,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
    ACTIONS(70), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PIPE,
    ACTIONS(68), 14,
      anon_sym_RPAREN,
      anon_sym_not,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_disjunction_operator,
      sym_conjuction_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_in,
      anon_sym_is,
  [1360] = 2,
    ACTIONS(74), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(72), 17,
      anon_sym_RPAREN,
      anon_sym_not,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_disjunction_operator,
      sym_conjuction_operator,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_in,
      anon_sym_is,
  [1386] = 2,
    ACTIONS(78), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(76), 17,
      anon_sym_RPAREN,
      anon_sym_not,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_disjunction_operator,
      sym_conjuction_operator,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_in,
      anon_sym_is,
  [1412] = 2,
    ACTIONS(82), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(80), 17,
      anon_sym_RPAREN,
      anon_sym_not,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_disjunction_operator,
      sym_conjuction_operator,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_in,
      anon_sym_is,
  [1438] = 2,
    ACTIONS(86), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(84), 17,
      anon_sym_RPAREN,
      anon_sym_not,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_disjunction_operator,
      sym_conjuction_operator,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_in,
      anon_sym_is,
  [1464] = 2,
    ACTIONS(90), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(88), 17,
      anon_sym_RPAREN,
      anon_sym_not,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_disjunction_operator,
      sym_conjuction_operator,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_in,
      anon_sym_is,
  [1490] = 2,
    ACTIONS(94), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(92), 17,
      anon_sym_RPAREN,
      anon_sym_not,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_disjunction_operator,
      sym_conjuction_operator,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_in,
      anon_sym_is,
  [1516] = 2,
    ACTIONS(98), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(96), 17,
      anon_sym_RPAREN,
      anon_sym_not,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_disjunction_operator,
      sym_conjuction_operator,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_in,
      anon_sym_is,
  [1542] = 2,
    ACTIONS(102), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(100), 17,
      anon_sym_RPAREN,
      anon_sym_not,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_disjunction_operator,
      sym_conjuction_operator,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_in,
      anon_sym_is,
  [1568] = 2,
    ACTIONS(106), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(104), 17,
      anon_sym_RPAREN,
      anon_sym_not,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_disjunction_operator,
      sym_conjuction_operator,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_in,
      anon_sym_is,
  [1594] = 2,
    ACTIONS(110), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(108), 17,
      anon_sym_RPAREN,
      anon_sym_not,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_disjunction_operator,
      sym_conjuction_operator,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_in,
      anon_sym_is,
  [1620] = 2,
    ACTIONS(114), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(112), 17,
      anon_sym_RPAREN,
      anon_sym_not,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_disjunction_operator,
      sym_conjuction_operator,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_in,
      anon_sym_is,
  [1646] = 2,
    ACTIONS(118), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(116), 17,
      anon_sym_RPAREN,
      anon_sym_not,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_disjunction_operator,
      sym_conjuction_operator,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_in,
      anon_sym_is,
  [1672] = 2,
    ACTIONS(122), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(120), 17,
      anon_sym_RPAREN,
      anon_sym_not,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_disjunction_operator,
      sym_conjuction_operator,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_in,
      anon_sym_is,
  [1698] = 2,
    ACTIONS(126), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(124), 17,
      anon_sym_RPAREN,
      anon_sym_not,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_disjunction_operator,
      sym_conjuction_operator,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_in,
      anon_sym_is,
  [1724] = 2,
    ACTIONS(130), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(128), 17,
      anon_sym_RPAREN,
      anon_sym_not,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_disjunction_operator,
      sym_conjuction_operator,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_in,
      anon_sym_is,
  [1750] = 2,
    ACTIONS(58), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(56), 17,
      anon_sym_RPAREN,
      anon_sym_not,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_disjunction_operator,
      sym_conjuction_operator,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_in,
      anon_sym_is,
  [1776] = 2,
    ACTIONS(134), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(132), 17,
      anon_sym_RPAREN,
      anon_sym_not,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_disjunction_operator,
      sym_conjuction_operator,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_in,
      anon_sym_is,
  [1802] = 2,
    ACTIONS(138), 4,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_PIPE,
      anon_sym_AMP,
    ACTIONS(136), 17,
      anon_sym_RPAREN,
      anon_sym_not,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_disjunction_operator,
      sym_conjuction_operator,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_PERCENT,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_in,
      anon_sym_is,
  [1828] = 5,
    ACTIONS(146), 1,
      anon_sym_PIPE,
    STATE(13), 1,
      sym_additive_operator,
    ACTIONS(142), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(144), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(140), 12,
      anon_sym_RPAREN,
      anon_sym_not,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      sym_disjunction_operator,
      sym_conjuction_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_in,
      anon_sym_is,
  [1857] = 6,
    ACTIONS(152), 1,
      anon_sym_not,
    ACTIONS(156), 1,
      anon_sym_is,
    STATE(12), 1,
      sym_relational_operator,
    ACTIONS(150), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(148), 5,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      sym_disjunction_operator,
      sym_conjuction_operator,
    ACTIONS(154), 5,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_in,
  [1885] = 6,
    ACTIONS(152), 1,
      anon_sym_not,
    ACTIONS(156), 1,
      anon_sym_is,
    STATE(12), 1,
      sym_relational_operator,
    ACTIONS(150), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(154), 5,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_in,
    ACTIONS(158), 5,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      sym_disjunction_operator,
      sym_conjuction_operator,
  [1913] = 2,
    ACTIONS(162), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(160), 12,
      anon_sym_RPAREN,
      anon_sym_not,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      sym_disjunction_operator,
      sym_conjuction_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_in,
      anon_sym_is,
  [1932] = 2,
    ACTIONS(166), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(164), 12,
      anon_sym_RPAREN,
      anon_sym_not,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      sym_disjunction_operator,
      sym_conjuction_operator,
      anon_sym_EQ_EQ,
      anon_sym_BANG_EQ,
      anon_sym_GT_EQ,
      anon_sym_LT_EQ,
      anon_sym_in,
      anon_sym_is,
  [1951] = 3,
    ACTIONS(170), 1,
      anon_sym_not,
    ACTIONS(172), 1,
      sym_camel_identifier,
    ACTIONS(168), 9,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_pascal_identifier,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      sym_integer,
  [1969] = 1,
    ACTIONS(174), 10,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_camel_identifier,
      sym_pascal_identifier,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      sym_integer,
  [1982] = 1,
    ACTIONS(168), 10,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_camel_identifier,
      sym_pascal_identifier,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      sym_integer,
  [1995] = 1,
    ACTIONS(176), 10,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_camel_identifier,
      sym_pascal_identifier,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      sym_integer,
  [2008] = 1,
    ACTIONS(178), 10,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_camel_identifier,
      sym_pascal_identifier,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      sym_integer,
  [2021] = 1,
    ACTIONS(180), 10,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      anon_sym_PLUS,
      anon_sym_DASH,
      sym_camel_identifier,
      sym_pascal_identifier,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
      sym_integer,
  [2034] = 6,
    ACTIONS(182), 1,
      anon_sym_RBRACE,
    ACTIONS(184), 1,
      sym_camel_identifier,
    ACTIONS(187), 1,
      sym_decorator_identifier,
    STATE(53), 2,
      sym_body_element,
      aux_sym_body_repeat1,
    STATE(82), 2,
      sym_decorator,
      aux_sym_block_repeat1,
    STATE(96), 2,
      sym_block,
      sym_property,
  [2056] = 6,
    ACTIONS(7), 1,
      sym_decorator_identifier,
    ACTIONS(190), 1,
      anon_sym_RBRACE,
    ACTIONS(192), 1,
      sym_camel_identifier,
    STATE(53), 2,
      sym_body_element,
      aux_sym_body_repeat1,
    STATE(82), 2,
      sym_decorator,
      aux_sym_block_repeat1,
    STATE(96), 2,
      sym_block,
      sym_property,
  [2078] = 6,
    ACTIONS(7), 1,
      sym_decorator_identifier,
    ACTIONS(192), 1,
      sym_camel_identifier,
    ACTIONS(194), 1,
      anon_sym_RBRACE,
    STATE(54), 2,
      sym_body_element,
      aux_sym_body_repeat1,
    STATE(82), 2,
      sym_decorator,
      aux_sym_block_repeat1,
    STATE(96), 2,
      sym_block,
      sym_property,
  [2100] = 5,
    ACTIONS(196), 1,
      anon_sym_LBRACE,
    ACTIONS(200), 1,
      anon_sym_LT,
    STATE(68), 1,
      sym_generic_args,
    STATE(98), 1,
      sym_body,
    ACTIONS(198), 3,
      anon_sym_RBRACE,
      sym_camel_identifier,
      sym_decorator_identifier,
  [2118] = 5,
    ACTIONS(202), 1,
      ts_builtin_sym_end,
    ACTIONS(204), 1,
      sym_camel_identifier,
    ACTIONS(207), 1,
      sym_decorator_identifier,
    STATE(57), 2,
      sym_block,
      aux_sym_program_repeat1,
    STATE(83), 2,
      sym_decorator,
      aux_sym_block_repeat1,
  [2136] = 5,
    ACTIONS(5), 1,
      sym_camel_identifier,
    ACTIONS(7), 1,
      sym_decorator_identifier,
    ACTIONS(210), 1,
      ts_builtin_sym_end,
    STATE(57), 2,
      sym_block,
      aux_sym_program_repeat1,
    STATE(83), 2,
      sym_decorator,
      aux_sym_block_repeat1,
  [2154] = 5,
    ACTIONS(196), 1,
      anon_sym_LBRACE,
    ACTIONS(200), 1,
      anon_sym_LT,
    STATE(69), 1,
      sym_generic_args,
    STATE(100), 1,
      sym_body,
    ACTIONS(212), 3,
      anon_sym_RBRACE,
      sym_camel_identifier,
      sym_decorator_identifier,
  [2172] = 6,
    ACTIONS(196), 1,
      anon_sym_LBRACE,
    ACTIONS(200), 1,
      anon_sym_LT,
    ACTIONS(214), 1,
      anon_sym_LPAREN,
    STATE(77), 1,
      sym_body,
    STATE(84), 1,
      sym_generic_args,
    STATE(103), 1,
      sym_extends_args,
  [2191] = 1,
    ACTIONS(216), 6,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      sym_disjunction_operator,
      sym_conjuction_operator,
  [2200] = 1,
    ACTIONS(218), 6,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      sym_disjunction_operator,
      sym_conjuction_operator,
  [2209] = 2,
    ACTIONS(222), 1,
      sym_conjuction_operator,
    ACTIONS(220), 5,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      sym_disjunction_operator,
  [2220] = 2,
    ACTIONS(222), 1,
      sym_conjuction_operator,
    ACTIONS(224), 5,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      sym_disjunction_operator,
  [2231] = 6,
    ACTIONS(196), 1,
      anon_sym_LBRACE,
    ACTIONS(200), 1,
      anon_sym_LT,
    ACTIONS(214), 1,
      anon_sym_LPAREN,
    STATE(85), 1,
      sym_body,
    STATE(86), 1,
      sym_generic_args,
    STATE(107), 1,
      sym_extends_args,
  [2250] = 1,
    ACTIONS(226), 5,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LPAREN,
      sym_camel_identifier,
      sym_decorator_identifier,
  [2258] = 2,
    ACTIONS(230), 1,
      sym_disjunction_operator,
    ACTIONS(228), 4,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_RBRACK,
      anon_sym_COMMA,
  [2268] = 3,
    ACTIONS(196), 1,
      anon_sym_LBRACE,
    STATE(97), 1,
      sym_body,
    ACTIONS(232), 3,
      anon_sym_RBRACE,
      sym_camel_identifier,
      sym_decorator_identifier,
  [2280] = 3,
    ACTIONS(196), 1,
      anon_sym_LBRACE,
    STATE(98), 1,
      sym_body,
    ACTIONS(198), 3,
      anon_sym_RBRACE,
      sym_camel_identifier,
      sym_decorator_identifier,
  [2292] = 1,
    ACTIONS(234), 5,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT,
      sym_camel_identifier,
      sym_decorator_identifier,
  [2300] = 3,
    ACTIONS(238), 1,
      anon_sym_COMMA,
    STATE(72), 1,
      aux_sym_expression_list_repeat1,
    ACTIONS(236), 3,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_RBRACK,
  [2312] = 3,
    ACTIONS(242), 1,
      anon_sym_COMMA,
    STATE(72), 1,
      aux_sym_expression_list_repeat1,
    ACTIONS(240), 3,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_RBRACK,
  [2324] = 4,
    ACTIONS(247), 1,
      aux_sym_single_quote_string_token1,
    ACTIONS(250), 1,
      sym_escape_sequence,
    STATE(73), 1,
      aux_sym_single_quote_string_repeat1,
    ACTIONS(245), 2,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [2338] = 3,
    ACTIONS(238), 1,
      anon_sym_COMMA,
    STATE(71), 1,
      aux_sym_expression_list_repeat1,
    ACTIONS(253), 3,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_RBRACK,
  [2350] = 3,
    ACTIONS(255), 1,
      sym_camel_identifier,
    ACTIONS(257), 1,
      sym_decorator_identifier,
    STATE(75), 2,
      sym_decorator,
      aux_sym_block_repeat1,
  [2361] = 1,
    ACTIONS(240), 4,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_RBRACK,
      anon_sym_COMMA,
  [2368] = 1,
    ACTIONS(260), 4,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_camel_identifier,
      sym_decorator_identifier,
  [2375] = 4,
    ACTIONS(262), 1,
      aux_sym_single_quote_string_token1,
    ACTIONS(264), 1,
      anon_sym_BQUOTE,
    ACTIONS(266), 1,
      sym_escape_sequence,
    STATE(73), 1,
      aux_sym_single_quote_string_repeat1,
  [2388] = 3,
    ACTIONS(268), 1,
      anon_sym_LPAREN,
    STATE(109), 1,
      sym_decorator_args,
    ACTIONS(270), 2,
      sym_camel_identifier,
      sym_decorator_identifier,
  [2399] = 4,
    ACTIONS(262), 1,
      aux_sym_single_quote_string_token1,
    ACTIONS(266), 1,
      sym_escape_sequence,
    ACTIONS(272), 1,
      anon_sym_SQUOTE,
    STATE(73), 1,
      aux_sym_single_quote_string_repeat1,
  [2412] = 1,
    ACTIONS(274), 4,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_camel_identifier,
      sym_decorator_identifier,
  [2419] = 3,
    ACTIONS(7), 1,
      sym_decorator_identifier,
    ACTIONS(276), 1,
      sym_camel_identifier,
    STATE(75), 2,
      sym_decorator,
      aux_sym_block_repeat1,
  [2430] = 3,
    ACTIONS(7), 1,
      sym_decorator_identifier,
    ACTIONS(278), 1,
      sym_camel_identifier,
    STATE(75), 2,
      sym_decorator,
      aux_sym_block_repeat1,
  [2441] = 4,
    ACTIONS(196), 1,
      anon_sym_LBRACE,
    ACTIONS(214), 1,
      anon_sym_LPAREN,
    STATE(91), 1,
      sym_body,
    STATE(110), 1,
      sym_extends_args,
  [2454] = 1,
    ACTIONS(280), 4,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_camel_identifier,
      sym_decorator_identifier,
  [2461] = 4,
    ACTIONS(196), 1,
      anon_sym_LBRACE,
    ACTIONS(214), 1,
      anon_sym_LPAREN,
    STATE(77), 1,
      sym_body,
    STATE(103), 1,
      sym_extends_args,
  [2474] = 1,
    ACTIONS(282), 4,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_camel_identifier,
      sym_decorator_identifier,
  [2481] = 4,
    ACTIONS(284), 1,
      anon_sym_DQUOTE,
    ACTIONS(286), 1,
      aux_sym_double_quote_string_token1,
    ACTIONS(288), 1,
      sym_escape_sequence,
    STATE(95), 1,
      aux_sym_double_quote_string_repeat1,
  [2494] = 4,
    ACTIONS(290), 1,
      anon_sym_SQUOTE,
    ACTIONS(292), 1,
      aux_sym_single_quote_string_token1,
    ACTIONS(294), 1,
      sym_escape_sequence,
    STATE(80), 1,
      aux_sym_single_quote_string_repeat1,
  [2507] = 1,
    ACTIONS(296), 4,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_camel_identifier,
      sym_decorator_identifier,
  [2514] = 1,
    ACTIONS(298), 4,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_camel_identifier,
      sym_decorator_identifier,
  [2521] = 4,
    ACTIONS(300), 1,
      aux_sym_single_quote_string_token1,
    ACTIONS(302), 1,
      anon_sym_BQUOTE,
    ACTIONS(304), 1,
      sym_escape_sequence,
    STATE(78), 1,
      aux_sym_single_quote_string_repeat1,
  [2534] = 1,
    ACTIONS(306), 4,
      anon_sym_RPAREN,
      anon_sym_GT,
      anon_sym_RBRACK,
      anon_sym_COMMA,
  [2541] = 4,
    ACTIONS(308), 1,
      anon_sym_DQUOTE,
    ACTIONS(310), 1,
      aux_sym_double_quote_string_token1,
    ACTIONS(313), 1,
      sym_escape_sequence,
    STATE(94), 1,
      aux_sym_double_quote_string_repeat1,
  [2554] = 4,
    ACTIONS(316), 1,
      anon_sym_DQUOTE,
    ACTIONS(318), 1,
      aux_sym_double_quote_string_token1,
    ACTIONS(320), 1,
      sym_escape_sequence,
    STATE(94), 1,
      aux_sym_double_quote_string_repeat1,
  [2567] = 1,
    ACTIONS(322), 3,
      anon_sym_RBRACE,
      sym_camel_identifier,
      sym_decorator_identifier,
  [2573] = 1,
    ACTIONS(324), 3,
      anon_sym_RBRACE,
      sym_camel_identifier,
      sym_decorator_identifier,
  [2579] = 1,
    ACTIONS(232), 3,
      anon_sym_RBRACE,
      sym_camel_identifier,
      sym_decorator_identifier,
  [2585] = 2,
    STATE(59), 1,
      sym_property_type,
    ACTIONS(326), 2,
      sym_camel_identifier,
      sym_pascal_identifier,
  [2593] = 1,
    ACTIONS(198), 3,
      anon_sym_RBRACE,
      sym_camel_identifier,
      sym_decorator_identifier,
  [2599] = 2,
    STATE(20), 1,
      sym_identifier_name,
    ACTIONS(21), 2,
      sym_camel_identifier,
      sym_pascal_identifier,
  [2607] = 2,
    STATE(56), 1,
      sym_property_type,
    ACTIONS(326), 2,
      sym_camel_identifier,
      sym_pascal_identifier,
  [2615] = 2,
    ACTIONS(196), 1,
      anon_sym_LBRACE,
    STATE(91), 1,
      sym_body,
  [2622] = 1,
    ACTIONS(328), 2,
      sym_camel_identifier,
      sym_decorator_identifier,
  [2627] = 2,
    ACTIONS(330), 1,
      anon_sym_COLON,
    ACTIONS(332), 1,
      sym_pascal_identifier,
  [2634] = 1,
    ACTIONS(334), 2,
      sym_camel_identifier,
      sym_decorator_identifier,
  [2639] = 2,
    ACTIONS(196), 1,
      anon_sym_LBRACE,
    STATE(77), 1,
      sym_body,
  [2646] = 2,
    ACTIONS(336), 1,
      anon_sym_COLON,
    ACTIONS(338), 1,
      sym_pascal_identifier,
  [2653] = 1,
    ACTIONS(340), 2,
      sym_camel_identifier,
      sym_decorator_identifier,
  [2658] = 2,
    ACTIONS(196), 1,
      anon_sym_LBRACE,
    STATE(81), 1,
      sym_body,
  [2665] = 1,
    ACTIONS(338), 1,
      sym_pascal_identifier,
  [2669] = 1,
    ACTIONS(342), 1,
      anon_sym_in,
  [2673] = 1,
    ACTIONS(344), 1,
      anon_sym_RPAREN,
  [2677] = 1,
    ACTIONS(346), 1,
      ts_builtin_sym_end,
  [2681] = 1,
    ACTIONS(348), 1,
      anon_sym_RPAREN,
  [2685] = 1,
    ACTIONS(350), 1,
      anon_sym_RPAREN,
  [2689] = 1,
    ACTIONS(352), 1,
      anon_sym_RPAREN,
  [2693] = 1,
    ACTIONS(332), 1,
      sym_pascal_identifier,
  [2697] = 1,
    ACTIONS(354), 1,
      anon_sym_LBRACE,
  [2701] = 1,
    ACTIONS(356), 1,
      anon_sym_GT,
  [2705] = 1,
    ACTIONS(358), 1,
      anon_sym_RBRACK,
};

static uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 95,
  [SMALL_STATE(4)] = 190,
  [SMALL_STATE(5)] = 282,
  [SMALL_STATE(6)] = 374,
  [SMALL_STATE(7)] = 466,
  [SMALL_STATE(8)] = 555,
  [SMALL_STATE(9)] = 644,
  [SMALL_STATE(10)] = 724,
  [SMALL_STATE(11)] = 801,
  [SMALL_STATE(12)] = 870,
  [SMALL_STATE(13)] = 936,
  [SMALL_STATE(14)] = 996,
  [SMALL_STATE(15)] = 1029,
  [SMALL_STATE(16)] = 1086,
  [SMALL_STATE(17)] = 1143,
  [SMALL_STATE(18)] = 1176,
  [SMALL_STATE(19)] = 1209,
  [SMALL_STATE(20)] = 1237,
  [SMALL_STATE(21)] = 1265,
  [SMALL_STATE(22)] = 1294,
  [SMALL_STATE(23)] = 1327,
  [SMALL_STATE(24)] = 1360,
  [SMALL_STATE(25)] = 1386,
  [SMALL_STATE(26)] = 1412,
  [SMALL_STATE(27)] = 1438,
  [SMALL_STATE(28)] = 1464,
  [SMALL_STATE(29)] = 1490,
  [SMALL_STATE(30)] = 1516,
  [SMALL_STATE(31)] = 1542,
  [SMALL_STATE(32)] = 1568,
  [SMALL_STATE(33)] = 1594,
  [SMALL_STATE(34)] = 1620,
  [SMALL_STATE(35)] = 1646,
  [SMALL_STATE(36)] = 1672,
  [SMALL_STATE(37)] = 1698,
  [SMALL_STATE(38)] = 1724,
  [SMALL_STATE(39)] = 1750,
  [SMALL_STATE(40)] = 1776,
  [SMALL_STATE(41)] = 1802,
  [SMALL_STATE(42)] = 1828,
  [SMALL_STATE(43)] = 1857,
  [SMALL_STATE(44)] = 1885,
  [SMALL_STATE(45)] = 1913,
  [SMALL_STATE(46)] = 1932,
  [SMALL_STATE(47)] = 1951,
  [SMALL_STATE(48)] = 1969,
  [SMALL_STATE(49)] = 1982,
  [SMALL_STATE(50)] = 1995,
  [SMALL_STATE(51)] = 2008,
  [SMALL_STATE(52)] = 2021,
  [SMALL_STATE(53)] = 2034,
  [SMALL_STATE(54)] = 2056,
  [SMALL_STATE(55)] = 2078,
  [SMALL_STATE(56)] = 2100,
  [SMALL_STATE(57)] = 2118,
  [SMALL_STATE(58)] = 2136,
  [SMALL_STATE(59)] = 2154,
  [SMALL_STATE(60)] = 2172,
  [SMALL_STATE(61)] = 2191,
  [SMALL_STATE(62)] = 2200,
  [SMALL_STATE(63)] = 2209,
  [SMALL_STATE(64)] = 2220,
  [SMALL_STATE(65)] = 2231,
  [SMALL_STATE(66)] = 2250,
  [SMALL_STATE(67)] = 2258,
  [SMALL_STATE(68)] = 2268,
  [SMALL_STATE(69)] = 2280,
  [SMALL_STATE(70)] = 2292,
  [SMALL_STATE(71)] = 2300,
  [SMALL_STATE(72)] = 2312,
  [SMALL_STATE(73)] = 2324,
  [SMALL_STATE(74)] = 2338,
  [SMALL_STATE(75)] = 2350,
  [SMALL_STATE(76)] = 2361,
  [SMALL_STATE(77)] = 2368,
  [SMALL_STATE(78)] = 2375,
  [SMALL_STATE(79)] = 2388,
  [SMALL_STATE(80)] = 2399,
  [SMALL_STATE(81)] = 2412,
  [SMALL_STATE(82)] = 2419,
  [SMALL_STATE(83)] = 2430,
  [SMALL_STATE(84)] = 2441,
  [SMALL_STATE(85)] = 2454,
  [SMALL_STATE(86)] = 2461,
  [SMALL_STATE(87)] = 2474,
  [SMALL_STATE(88)] = 2481,
  [SMALL_STATE(89)] = 2494,
  [SMALL_STATE(90)] = 2507,
  [SMALL_STATE(91)] = 2514,
  [SMALL_STATE(92)] = 2521,
  [SMALL_STATE(93)] = 2534,
  [SMALL_STATE(94)] = 2541,
  [SMALL_STATE(95)] = 2554,
  [SMALL_STATE(96)] = 2567,
  [SMALL_STATE(97)] = 2573,
  [SMALL_STATE(98)] = 2579,
  [SMALL_STATE(99)] = 2585,
  [SMALL_STATE(100)] = 2593,
  [SMALL_STATE(101)] = 2599,
  [SMALL_STATE(102)] = 2607,
  [SMALL_STATE(103)] = 2615,
  [SMALL_STATE(104)] = 2622,
  [SMALL_STATE(105)] = 2627,
  [SMALL_STATE(106)] = 2634,
  [SMALL_STATE(107)] = 2639,
  [SMALL_STATE(108)] = 2646,
  [SMALL_STATE(109)] = 2653,
  [SMALL_STATE(110)] = 2658,
  [SMALL_STATE(111)] = 2665,
  [SMALL_STATE(112)] = 2669,
  [SMALL_STATE(113)] = 2673,
  [SMALL_STATE(114)] = 2677,
  [SMALL_STATE(115)] = 2681,
  [SMALL_STATE(116)] = 2685,
  [SMALL_STATE(117)] = 2689,
  [SMALL_STATE(118)] = 2693,
  [SMALL_STATE(119)] = 2697,
  [SMALL_STATE(120)] = 2701,
  [SMALL_STATE(121)] = 2705,
};

static TSParseActionEntry ts_parse_actions[] = {
  [0] = {.count = 0, .reusable = false},
  [1] = {.count = 1, .reusable = false}, RECOVER(),
  [3] = {.count = 1, .reusable = true}, REDUCE(sym_program, 0),
  [5] = {.count = 1, .reusable = true}, SHIFT(118),
  [7] = {.count = 1, .reusable = true}, SHIFT(79),
  [9] = {.count = 1, .reusable = true}, SHIFT(8),
  [11] = {.count = 1, .reusable = true}, SHIFT(34),
  [13] = {.count = 1, .reusable = false}, SHIFT(10),
  [15] = {.count = 1, .reusable = true}, SHIFT(5),
  [17] = {.count = 1, .reusable = true}, SHIFT(51),
  [19] = {.count = 1, .reusable = false}, SHIFT(19),
  [21] = {.count = 1, .reusable = true}, SHIFT(19),
  [23] = {.count = 1, .reusable = true}, SHIFT(88),
  [25] = {.count = 1, .reusable = true}, SHIFT(89),
  [27] = {.count = 1, .reusable = true}, SHIFT(92),
  [29] = {.count = 1, .reusable = true}, SHIFT(28),
  [31] = {.count = 1, .reusable = true}, SHIFT(106),
  [33] = {.count = 1, .reusable = true}, REDUCE(sym_identifier, 1),
  [35] = {.count = 1, .reusable = false}, REDUCE(sym_identifier, 1),
  [37] = {.count = 1, .reusable = true}, SHIFT(101),
  [39] = {.count = 1, .reusable = true}, REDUCE(sym_identifier, 2),
  [41] = {.count = 1, .reusable = false}, REDUCE(sym_identifier, 2),
  [43] = {.count = 1, .reusable = true}, REDUCE(aux_sym_identifier_repeat1, 2),
  [45] = {.count = 1, .reusable = false}, REDUCE(aux_sym_identifier_repeat1, 2),
  [47] = {.count = 2, .reusable = true}, REDUCE(aux_sym_identifier_repeat1, 2), SHIFT_REPEAT(101),
  [50] = {.count = 1, .reusable = true}, REDUCE(sym_identifier_name, 1),
  [52] = {.count = 1, .reusable = false}, REDUCE(sym_identifier_name, 1),
  [54] = {.count = 1, .reusable = true}, SHIFT(2),
  [56] = {.count = 1, .reusable = true}, REDUCE(sym_factor, 1),
  [58] = {.count = 1, .reusable = false}, REDUCE(sym_factor, 1),
  [60] = {.count = 1, .reusable = true}, REDUCE(sym_additive_expression, 3),
  [62] = {.count = 1, .reusable = false}, REDUCE(sym_additive_expression, 3),
  [64] = {.count = 1, .reusable = true}, SHIFT(52),
  [66] = {.count = 1, .reusable = false}, SHIFT(52),
  [68] = {.count = 1, .reusable = true}, REDUCE(sym_additive_expression, 1),
  [70] = {.count = 1, .reusable = false}, REDUCE(sym_additive_expression, 1),
  [72] = {.count = 1, .reusable = true}, REDUCE(sym_single_quote_string, 3),
  [74] = {.count = 1, .reusable = false}, REDUCE(sym_single_quote_string, 3),
  [76] = {.count = 1, .reusable = true}, REDUCE(sym_string, 1),
  [78] = {.count = 1, .reusable = false}, REDUCE(sym_string, 1),
  [80] = {.count = 1, .reusable = true}, REDUCE(sym_template_string, 3),
  [82] = {.count = 1, .reusable = false}, REDUCE(sym_template_string, 3),
  [84] = {.count = 1, .reusable = true}, REDUCE(sym_function_call, 4),
  [86] = {.count = 1, .reusable = false}, REDUCE(sym_function_call, 4),
  [88] = {.count = 1, .reusable = true}, REDUCE(sym_number, 1),
  [90] = {.count = 1, .reusable = false}, REDUCE(sym_number, 1),
  [92] = {.count = 1, .reusable = true}, REDUCE(sym_double_quote_string, 3),
  [94] = {.count = 1, .reusable = false}, REDUCE(sym_double_quote_string, 3),
  [96] = {.count = 1, .reusable = true}, REDUCE(sym_list, 3),
  [98] = {.count = 1, .reusable = false}, REDUCE(sym_list, 3),
  [100] = {.count = 1, .reusable = true}, REDUCE(sym_factor, 3),
  [102] = {.count = 1, .reusable = false}, REDUCE(sym_factor, 3),
  [104] = {.count = 1, .reusable = true}, REDUCE(sym_template_string, 2),
  [106] = {.count = 1, .reusable = false}, REDUCE(sym_template_string, 2),
  [108] = {.count = 1, .reusable = true}, REDUCE(sym_single_quote_string, 2),
  [110] = {.count = 1, .reusable = false}, REDUCE(sym_single_quote_string, 2),
  [112] = {.count = 1, .reusable = true}, REDUCE(sym_function_call, 3),
  [114] = {.count = 1, .reusable = false}, REDUCE(sym_function_call, 3),
  [116] = {.count = 1, .reusable = true}, REDUCE(sym_unary_expression, 2),
  [118] = {.count = 1, .reusable = false}, REDUCE(sym_unary_expression, 2),
  [120] = {.count = 1, .reusable = true}, REDUCE(sym_literal, 1),
  [122] = {.count = 1, .reusable = false}, REDUCE(sym_literal, 1),
  [124] = {.count = 1, .reusable = true}, REDUCE(sym_unsigned_constant, 1),
  [126] = {.count = 1, .reusable = false}, REDUCE(sym_unsigned_constant, 1),
  [128] = {.count = 1, .reusable = true}, REDUCE(sym_multiplicative_expression, 1),
  [130] = {.count = 1, .reusable = false}, REDUCE(sym_multiplicative_expression, 1),
  [132] = {.count = 1, .reusable = true}, REDUCE(sym_multiplicative_expression, 3),
  [134] = {.count = 1, .reusable = false}, REDUCE(sym_multiplicative_expression, 3),
  [136] = {.count = 1, .reusable = true}, REDUCE(sym_double_quote_string, 2),
  [138] = {.count = 1, .reusable = false}, REDUCE(sym_double_quote_string, 2),
  [140] = {.count = 1, .reusable = true}, REDUCE(sym_arithmetic_expression, 1),
  [142] = {.count = 1, .reusable = false}, REDUCE(sym_arithmetic_expression, 1),
  [144] = {.count = 1, .reusable = true}, SHIFT(50),
  [146] = {.count = 1, .reusable = false}, SHIFT(50),
  [148] = {.count = 1, .reusable = true}, REDUCE(sym_conjuction_expression, 3),
  [150] = {.count = 1, .reusable = false}, SHIFT(49),
  [152] = {.count = 1, .reusable = true}, SHIFT(112),
  [154] = {.count = 1, .reusable = true}, SHIFT(49),
  [156] = {.count = 1, .reusable = true}, SHIFT(47),
  [158] = {.count = 1, .reusable = true}, REDUCE(sym_negation_expression, 1),
  [160] = {.count = 1, .reusable = true}, REDUCE(sym_relational_expression, 3),
  [162] = {.count = 1, .reusable = false}, REDUCE(sym_relational_expression, 3),
  [164] = {.count = 1, .reusable = true}, REDUCE(sym_relational_expression, 1),
  [166] = {.count = 1, .reusable = false}, REDUCE(sym_relational_expression, 1),
  [168] = {.count = 1, .reusable = true}, REDUCE(sym_relational_operator, 1),
  [170] = {.count = 1, .reusable = false}, SHIFT(48),
  [172] = {.count = 1, .reusable = false}, REDUCE(sym_relational_operator, 1),
  [174] = {.count = 1, .reusable = true}, REDUCE(sym_relational_operator, 2),
  [176] = {.count = 1, .reusable = true}, REDUCE(sym_additive_operator, 1),
  [178] = {.count = 1, .reusable = true}, REDUCE(sym_unary_operator, 1),
  [180] = {.count = 1, .reusable = true}, REDUCE(sym_multiplicative_operator, 1),
  [182] = {.count = 1, .reusable = true}, REDUCE(aux_sym_body_repeat1, 2),
  [184] = {.count = 2, .reusable = true}, REDUCE(aux_sym_body_repeat1, 2), SHIFT_REPEAT(105),
  [187] = {.count = 2, .reusable = true}, REDUCE(aux_sym_body_repeat1, 2), SHIFT_REPEAT(79),
  [190] = {.count = 1, .reusable = true}, SHIFT(87),
  [192] = {.count = 1, .reusable = true}, SHIFT(105),
  [194] = {.count = 1, .reusable = true}, SHIFT(90),
  [196] = {.count = 1, .reusable = true}, SHIFT(55),
  [198] = {.count = 1, .reusable = true}, REDUCE(sym_property, 4),
  [200] = {.count = 1, .reusable = true}, SHIFT(4),
  [202] = {.count = 1, .reusable = true}, REDUCE(aux_sym_program_repeat1, 2),
  [204] = {.count = 2, .reusable = true}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(118),
  [207] = {.count = 2, .reusable = true}, REDUCE(aux_sym_program_repeat1, 2), SHIFT_REPEAT(79),
  [210] = {.count = 1, .reusable = true}, REDUCE(sym_program, 1),
  [212] = {.count = 1, .reusable = true}, REDUCE(sym_property, 3),
  [214] = {.count = 1, .reusable = true}, SHIFT(6),
  [216] = {.count = 1, .reusable = true}, REDUCE(sym_conjuction_expression, 1),
  [218] = {.count = 1, .reusable = true}, REDUCE(sym_negation_expression, 2),
  [220] = {.count = 1, .reusable = true}, REDUCE(sym_disjunction_expression, 1),
  [222] = {.count = 1, .reusable = true}, SHIFT(11),
  [224] = {.count = 1, .reusable = true}, REDUCE(sym_disjunction_expression, 3),
  [226] = {.count = 1, .reusable = true}, REDUCE(sym_generic_args, 3),
  [228] = {.count = 1, .reusable = true}, REDUCE(sym_boolean_expression, 1),
  [230] = {.count = 1, .reusable = true}, SHIFT(9),
  [232] = {.count = 1, .reusable = true}, REDUCE(sym_property, 5),
  [234] = {.count = 1, .reusable = true}, REDUCE(sym_property_type, 1),
  [236] = {.count = 1, .reusable = true}, REDUCE(sym_expression_list, 2),
  [238] = {.count = 1, .reusable = true}, SHIFT(7),
  [240] = {.count = 1, .reusable = true}, REDUCE(aux_sym_expression_list_repeat1, 2),
  [242] = {.count = 2, .reusable = true}, REDUCE(aux_sym_expression_list_repeat1, 2), SHIFT_REPEAT(7),
  [245] = {.count = 1, .reusable = false}, REDUCE(aux_sym_single_quote_string_repeat1, 2),
  [247] = {.count = 2, .reusable = true}, REDUCE(aux_sym_single_quote_string_repeat1, 2), SHIFT_REPEAT(73),
  [250] = {.count = 2, .reusable = false}, REDUCE(aux_sym_single_quote_string_repeat1, 2), SHIFT_REPEAT(73),
  [253] = {.count = 1, .reusable = true}, REDUCE(sym_expression_list, 1),
  [255] = {.count = 1, .reusable = true}, REDUCE(aux_sym_block_repeat1, 2),
  [257] = {.count = 2, .reusable = true}, REDUCE(aux_sym_block_repeat1, 2), SHIFT_REPEAT(79),
  [260] = {.count = 1, .reusable = true}, REDUCE(sym_block, 4),
  [262] = {.count = 1, .reusable = true}, SHIFT(73),
  [264] = {.count = 1, .reusable = false}, SHIFT(26),
  [266] = {.count = 1, .reusable = false}, SHIFT(73),
  [268] = {.count = 1, .reusable = true}, SHIFT(3),
  [270] = {.count = 1, .reusable = true}, REDUCE(sym_decorator, 1),
  [272] = {.count = 1, .reusable = false}, SHIFT(24),
  [274] = {.count = 1, .reusable = true}, REDUCE(sym_block, 6),
  [276] = {.count = 1, .reusable = true}, SHIFT(108),
  [278] = {.count = 1, .reusable = true}, SHIFT(111),
  [280] = {.count = 1, .reusable = true}, REDUCE(sym_block, 3),
  [282] = {.count = 1, .reusable = true}, REDUCE(sym_body, 3),
  [284] = {.count = 1, .reusable = false}, SHIFT(41),
  [286] = {.count = 1, .reusable = true}, SHIFT(95),
  [288] = {.count = 1, .reusable = false}, SHIFT(95),
  [290] = {.count = 1, .reusable = false}, SHIFT(33),
  [292] = {.count = 1, .reusable = true}, SHIFT(80),
  [294] = {.count = 1, .reusable = false}, SHIFT(80),
  [296] = {.count = 1, .reusable = true}, REDUCE(sym_body, 2),
  [298] = {.count = 1, .reusable = true}, REDUCE(sym_block, 5),
  [300] = {.count = 1, .reusable = true}, SHIFT(78),
  [302] = {.count = 1, .reusable = false}, SHIFT(32),
  [304] = {.count = 1, .reusable = false}, SHIFT(78),
  [306] = {.count = 1, .reusable = true}, REDUCE(sym_expression, 1),
  [308] = {.count = 1, .reusable = false}, REDUCE(aux_sym_double_quote_string_repeat1, 2),
  [310] = {.count = 2, .reusable = true}, REDUCE(aux_sym_double_quote_string_repeat1, 2), SHIFT_REPEAT(94),
  [313] = {.count = 2, .reusable = false}, REDUCE(aux_sym_double_quote_string_repeat1, 2), SHIFT_REPEAT(94),
  [316] = {.count = 1, .reusable = false}, SHIFT(29),
  [318] = {.count = 1, .reusable = true}, SHIFT(94),
  [320] = {.count = 1, .reusable = false}, SHIFT(94),
  [322] = {.count = 1, .reusable = true}, REDUCE(sym_body_element, 1),
  [324] = {.count = 1, .reusable = true}, REDUCE(sym_property, 6),
  [326] = {.count = 1, .reusable = true}, SHIFT(70),
  [328] = {.count = 1, .reusable = true}, REDUCE(sym_decorator_args, 3),
  [330] = {.count = 1, .reusable = true}, SHIFT(99),
  [332] = {.count = 1, .reusable = true}, SHIFT(65),
  [334] = {.count = 1, .reusable = true}, REDUCE(sym_decorator_args, 2),
  [336] = {.count = 1, .reusable = true}, SHIFT(102),
  [338] = {.count = 1, .reusable = true}, SHIFT(60),
  [340] = {.count = 1, .reusable = true}, REDUCE(sym_decorator, 2),
  [342] = {.count = 1, .reusable = true}, SHIFT(48),
  [344] = {.count = 1, .reusable = true}, SHIFT(104),
  [346] = {.count = 1, .reusable = true},  ACCEPT_INPUT(),
  [348] = {.count = 1, .reusable = true}, SHIFT(31),
  [350] = {.count = 1, .reusable = true}, SHIFT(27),
  [352] = {.count = 1, .reusable = true}, SHIFT(119),
  [354] = {.count = 1, .reusable = true}, REDUCE(sym_extends_args, 3),
  [356] = {.count = 1, .reusable = true}, SHIFT(66),
  [358] = {.count = 1, .reusable = true}, SHIFT(30),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_Haiku(void) {
  static TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .symbol_metadata = ts_symbol_metadata,
    .parse_table = (const unsigned short *)ts_parse_table,
    .small_parse_table = (const uint16_t *)ts_small_parse_table,
    .small_parse_table_map = (const uint32_t *)ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .lex_modes = ts_lex_modes,
    .symbol_names = ts_symbol_names,
    .public_symbol_map = ts_symbol_map,
    .alias_sequences = (const TSSymbol *)ts_alias_sequences,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .lex_fn = ts_lex,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
